### ISSUE TITLE
ParseException()

### ISSUE THREAD

**Issue by sdizazzo** [siddhantgoel/streaming-form-data#1]
Hi!

I'm having trouble parsing a form streamed through uwsgi.  I get the error below.  I tried to track it down, but the closest I could get was that the byte was not a hyphen.  The traceback seems to show it erroring there, but I verified the character being passed in was indeed a hyphen (45).  Tried to print debugging info from within the .pyx, but couldn't get messages to show up in the terminal.  Never used cython, so not sure of the internals.

Thanks in advance for your help.

~Sean

```
  File "/usr/local/lib/python2.7/dist-packages/upload/upload.py", line 388, in upload
    parser.data_received(b)
  File "/usr/local/lib/python2.7/dist-packages/streaming_form_data/parser.py", line 53, in data_received
    self._parser.data_received(data)
  File "streaming_form_data/_parser.pyx", line 150, in streaming_form_data._parser._Parser.data_received (streaming_form_data/_parser.c:3929)
  File "streaming_form_data/_parser.pyx", line 172, in streaming_form_data._parser._Parser.data_received (streaming_form_data/_parser.c:3875)
  File "streaming_form_data/_parser.pyx", line 184, in streaming_form_data._parser._Parser._parse (streaming_form_data/_parser.c:4148)
streaming_form_data._parser._Failed
```

**Comment by siddhantgoel** [comment]
Hey Sean, thanks for the bug report! Could you please attach the raw form body? That would be helpful for debugging.

**Comment by sdizazzo** [comment]
Thanks for getting back to me!!  Attached is the raw form.  I changed a few little details since its proprietary.

[form.dat.zip](https://github.com/siddhantgoel/streaming-form-data/files/1033883/form.dat.zip)

**Comment by sdizazzo** [comment]
Actually...I guess that was not the whole thing. Thats where it barfed.  Right at the end.  Attached is the entire thing including the closing boundary marker.
[form_full.dat.zip](https://github.com/siddhantgoel/streaming-form-data/files/1033900/form_full.dat.zip)

**Comment by sdizazzo** [comment]
It fails in the binary data at exactly 4096 bytes every time.  Even with different input data.

**Comment by siddhantgoel** [comment]
Thanks for uploading the form data! I'm traveling currently so I won't be able to take a look immediately. Sorry about that! But I'll definitely get to this in a few days.

**Comment by siddhantgoel** [comment]
Right, I haven't tested this with Python 2.7. Currently only Python 3 has been tested, but you're right - I should probably update the README.

Btw if you have it working with Python 2.7, would you like to open a pull request? 2.7 support would be quite awesome.

**Comment by sdizazzo** [comment]
It's the least I can do.  Thanks for writing this!  It's really just a few simple changes.  Not sure if it will break anything in Python 3.

**Comment by siddhantgoel** [comment]
Awesome! [Six](https://pythonhosted.org/six/) might come in handy when making compatibility changes.

**Comment by siddhantgoel** [comment]
I added #2, so I'll close this issue.
