### ISSUE TITLE
(FastAPI) forward multi-file streaming to httpx POST request, without writing to disk?

### ISSUE THREAD

**Issue by hsunami10** [siddhantgoel/streaming-form-data#114]
Just like the title says! I’ve noticed that the use of `FileTarget` writes to disk. But, for my use case, I want to forward multiple files to a `httpx` POST request. I’ve already implemented [this answer here](https://stackoverflow.com/a/73443824), but it still writes to disk. Is there any way to do this without writing to the filesystem, and instead keeping streaming directly to another HTTP request? (thus keeping memory usage low)

**Comment by hsunami10** [comment]
so it looks like I'll have to make a custom class of sorts - and implement `on_data_received` and `pop_lines` myself, similar to `CSVTarget`. but the problem is, I'm not sure how to stream `on_data_received` to a httpx.post request's form data.

**Comment by siddhantgoel** [comment]
What's your setup? Are you directly uploading to the server, or are you uploading to a server that in turn uploads to a server? You need streaming-form-data only in the second case.

If you're directly uploading to a server (the first scenario I mentioned), I think just an `httpx.post` should be enough. According to https://www.python-httpx.org/advanced/clients/#multipart-file-encoding:

> It is safe to upload large files this way. File uploads are streaming by default, meaning that only one chunk will be loaded into memory at a time.

**Comment by hsunami10** [comment]
@siddhantgoel mine is the second case, where I'm uploading to a server that "forwards" the uploading to another server. The FastAPI app uses `streaming-form-data` and (ideally) should use `httpx.post` to upload to another server.

how would I use the `on_data_received` to forward those bytes to another streaming upload?

**Comment by siddhantgoel** [comment]
OK, yes in that case a custom target might work, at least from the client side. I haven't looked at the StackOverflow answer in too much detail. But from a first glance it seems to use `FileTarget` which is probably the reason the file is being written to disk. Have you tried creating a new target by inheriting `BaseTarget`?

**Comment by hsunami10** [comment]
yeah I was thinking of that - I'll try it in a couple days and let you know if it works! will post the solution here if it does

**Comment by hsunami10** [comment]
figured it out!

```python
import asyncio

from streaming_form_data.targets import BaseTarget  # type: ignore[import-untyped]

MAX_FILE_SIZE = 10 * 1024 * 1024 * 1024  # 10GB
MAX_REQUEST_BODY_SIZE = MAX_FILE_SIZE + 1024  # account for headers + extra bytes


class MaxBodySizeException(Exception):
    def __init__(self, body_len: int):
        self.body_len = body_len


class MaxFileSizeException(Exception):
    def __init__(self, body_len: int):
        self.body_len = body_len


class MaxSizeValidator:
    def __init__(
        self,
        max_size: int,
        exception: type[MaxBodySizeException] | type[MaxFileSizeException],
    ):
        self.body_len = 0
        self.max_size = max_size
        self.exception = exception

    def __call__(self, chunk: bytes):
        self.body_len += len(chunk)
        if self.body_len > self.max_size:
            raise self.exception(body_len=self.body_len)


class MaxSizeValidatorTarget(BaseTarget):
    def __init__(self, max_size: int, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._validator = MaxSizeValidator(max_size, MaxFileSizeException)

    def on_data_received(self, _: bytes):
        pass


class StreamingTarget(BaseTarget):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.chunks: asyncio.Queue[bytes | None] = asyncio.Queue(maxsize=10)

    async def _add_chunk(self, chunk: bytes | None):
        await self.chunks.put(chunk)

    def on_data_received(self, chunk: bytes):
        asyncio.ensure_future(self._add_chunk(chunk))

    def on_finish(self):
        asyncio.ensure_future(self._add_chunk(None))

```

The key is to have a generator that "gets" from the chunks Queue:
```python
streaming_target = StreamingTarget(
    validator=MaxSizeValidator(max_size=MAX_FILE_SIZE, exception=MaxFileSizeException)
)


async def generator():
    while True:
        chunk = await streaming_target.chunks.get()
        if chunk is None:
            break
        yield chunk
```
And then you can pass `generator()` into the HTTPX request!
