### ISSUE TITLE
type hints

### ISSUE THREAD

**Issue by kolomenkin** [siddhantgoel/streaming-form-data#28]
Hi, I would like to propose adding type hint information to the library.

The question is how it is better to do:
1) Use standalone .pyi file. It will not modify sources, but will need to duplicate declarations in .pyi.
2) Embed type information into the code. This may require Python 3.5+ (I'm not sure 100%). But type info will be integrated with the code. No code duplication.

What do you think?

**Comment by siddhantgoel** [comment]
From my side embedding type information into the code would be the way to go. Python 3.x [seems to support](https://mypy.readthedocs.io/en/latest/cheat_sheet_py3.html) the annotation syntax which we can use.

I would propose to do it now only for the pure-python source files (`parser.py`, `targets.py`, and `validators.py`). I'm currently not 100% sure how Cython works with the new type hinting syntax so I would like to have a deeper look there in the next days. Besides, a lot of the Cython code is typed already.

Do you also then plan to integrate `mypy` as a CI step in Travis?

**Comment by kolomenkin** [comment]
sure, mypy is a must if type hints are used.

**Comment by siddhantgoel** [comment]
I'll mark this issue as closed since we already have quite a few type annotations, and `make lint-mypy` runs in CI.
