### ISSUE TITLE
Multiple files?

### ISSUE THREAD

**Issue by inaod568** [siddhantgoel/streaming-form-data#30]
Hi,
How would I apply this to multiple files? 

Thanks

**Comment by siddhantgoel** [comment]
Do you mean multiple file inputs or one input where multiple files can be selected?

**Comment by inaod568** [comment]
Yeah, one input where multiple files can be selected.

**Comment by siddhantgoel** [comment]
At the moment we don't support that. I'll leave this issue open though. Could be a nice thing to implement next.

**Comment by guibos** [comment]
This functionality would be interesting.

**Comment by shaljam** [comment]
I came up with the following and it seems to be working. Note that I am sending all the files with the same field name.

```
from streaming_form_data.targets import BaseTarget

class MultiFileTarget(BaseTarget):
    def __init__(self, dirpath, allow_overwrite=True, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.dirpath = dirpath

        self._mode = 'wb' if allow_overwrite else 'xb'
        self._fd = None
        self.count = 0
        self.filenames = []
        self.content_types = []

    def on_start(self):
        print(f'on_start {self.multipart_filename}')
        self.count += 1
        self._fd = open(self.dirpath.joinpath(f'{self.count}'), self._mode)

    def on_data_received(self, chunk: bytes):
        self._fd.write(chunk)

    def on_finish(self):
        print(f'on_finish {self.multipart_filename} {self.multipart_content_type}')
        self.filenames.append(self.multipart_filename)
        self.content_types.append(self.multipart_content_type)
        self._fd.close()
```

`multipart_filename` is also available before opening the file. So, one may use it there. But, the `multipart_content_type` is available inside `on_finish`.

**Comment by siddhantgoel** [comment]
@shaljam are you sending all the files as different files inputs or one single input? As per my understanding, this is not that straight forward. Implementing support for multiple files would require changes inside the parser itself, as it'll need to be able to support `multipart/mixed` content type

**Comment by shaljam** [comment]
@siddhantgoel I am manually adding all the files to a JavaScript `FormData` with the same form field name (`files`).

```
var files = [] // list of JavaScript files selected by the user
var data = new FormData()

var url = '/path/to/upload'

files.forEach(f => {
  data.append('files', f)
})

var config = {
  onUploadProgress: progressEvent => {
    var percentCompleted = Math.round(
      (progressEvent.loaded * 100) / progressEvent.total
    )
    console.log(percentCompleted)
  }
}

axios
  .post(url, data, config)
  .then(res => {
    console.log(res)
  })
  .catch(function(err) {
    console.log(err)
  })

```

**Comment by siddhantgoel** [comment]
@shaljam could you check what happens if you don't use javascript, and instead just use a plain HTML form for selecting multiple files? does it still work in that case?

**Comment by shaljam** [comment]
It does work with a form.
I changed the flask example here: https://github.com/shaljam/streaming-form-data/commit/b32f73e3131f59ca114cffd66c6c45ae1dd749e8

POST data also looks like the following with most of file contents removed:

```
-----------------------------334262943931945903063393909723
Content-Disposition: form-data; name="file"; filename="panda.jpeg"
Content-Type: image/jpeg

ÿØÿàJFIF``ÿÛC
...	
=<ÀQEãðÉíøÐ-Ä»Ù`qùÑEW¸ýÚêO4Õj÷céEDìÌyéMQHóGJ( aGJ( 0ô¢½9Q@4QEÿÙ
-----------------------------334262943931945903063393909723
Content-Disposition: form-data; name="file"; filename="panda2.jpeg"
Content-Type: image/jpeg

ÿØÿàJFIFHHÿáExifMM*JR(iZHH  â $ÿí8Photoshop 3.08BIM8BIM%ÔÙ²é	ìøB~ÿÂ$âÿÄ	
...
±h$ò¥Ãr° m ´Ì\N&¥YJlXDÎi"r¹Rh^bÕNÇÜ9z$98êÍz ØÐ¾a-¶P([¢Ä-¨Öü]|ßjYç2}I°édî<zH%ÕtÌ·¹ª}ºdÂ©ÙsJÒÜA¥ÑA«"ÂyôW%âB	/¥B7µÊ(cE¨uÒ'ð!'Xôµ1#@2$E¬ÊÜ7sÅÊª±ÓôJfT|ÈÐ½|Þ	wgÙ/iß2À]ä{òIOø«q	¤É'lA eÐ@ußRÕlªÿÙ
-----------------------------334262943931945903063393909723--

```

**Comment by siddhantgoel** [comment]
Interesting, thanks for the info. I'll play around with this locally to figure out how we can update the API to best accommodate this feature.

The `MultiFileTarget` you wrote would be useful in any case though, independent of this feature. Except that I would suggest renaming it to `DirectoryTarget` and renaming the files being written to something other than the `count` variable. One suggestion would be to sanitize the `multipart_filename` variable and use that instead.

**Comment by shaljam** [comment]
@siddhantgoel In my use case, I needed the uploaded files to be named in that format. But, generally you are correct.
Also while you are at it, I suggest supporting directories also. Take a [webkitdirectory](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#webkitdirectory) attribute. In this case multiple files and directories (if combined with the `multiple` attribute) could be uploaded. In this case the files would have the `webkitRelativePath` property, denoting the relative path for the file. So the `DirectoryTarget` should create the directories also when needed.

**Comment by siddhantgoel** [comment]
`webkitdirectory` doesn't seem to be standardized at the moment, so I would prioritize it rather low. I'll check how directory support otherwise looks like.

**Comment by siddhantgoel** [comment]
Thanks to the work by @NteRySin, `v1.10.0` contains a `DirectoryTarget` which should achieve this.
