### ISSUE TITLE
Content-Type from FileTarget

### ISSUE THREAD

**Issue by QuadX23** [siddhantgoel/streaming-form-data#31]
How to get multipart Content-Type from FileTarget?
Content-Disposition: form-data; name="file"; filename="Webp.net-resizeimage.png"\r\n
Content-Type: image/png\r\n\r\n
image/png in this case

**Comment by siddhantgoel** [comment]
This is not implemented yet. I'll consider including this in the next release.

**Comment by siddhantgoel** [comment]
I just pushed `v1.5` to PyPI which makes the content type available under the `multipart_content_type` variable in `Target` objects (including `FileTarget`). Please try it out and let me know if something doesn't work!
