### ISSUE TITLE
Python 3 installation issue

### ISSUE THREAD

**Issue by mephi42** [siddhantgoel/streaming-form-data#32]
When I install `streaming-form-data` from `requirements.txt` or as below:

```
$ python3 -m pip install --user 'streaming-form-data == 1.5.1'
```

I'm getting the following issue:

```
$ python3 -c 'import streaming_form_data'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "$HOME/.local/lib/python3.7/site-packages/streaming_form_data/__init__.py", line 1, in <module>
    from streaming_form_data.parser import (  # NOQA
  File "$HOME/.local/lib/python3.7/site-packages/streaming_form_data/parser.py", line 4, in <module>
    from streaming_form_data._parser import ErrorGroup, _Parser  # type: ignore
ImportError: $HOME/.local/lib/python3.7/site-packages/streaming_form_data/_parser.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8
```

I think the problem is that the shared object ends up being built for python2 (which is also installed).

At the same time, installing by doing `git clone` + `python3 setup.py` works fine.

**Comment by siddhantgoel** [comment]
Interesting. When releasing on PyPI, I only upload the source distribution. So this sounds like some local installation issue. To verify, I also just installed this package in a fresh virtualenv via PyPI and it worked fine.

Are you using the system provided Python or a local build? Which version of Python is it? Also, are you inside a virtualenv?

**Comment by mephi42** [comment]
You are right, this must be a local issue. Fresh venv worked (because there is no Py2 I assume):

```
$ virtualenv py3 --python=python3
$ . py3/bin/activate
$ python3 -m pip install --no-cache-dir 'streaming-form-data == 1.5.1'
$ python3 -c 'import streaming_form_data'
```

However, this also works:

```
$ docker run -it --rm ubuntu:18.04
# apt update && apt install -y python python-pip python3 python3-pip pypy pypy3
# python3 -m pip install --user --no-cache-dir 'streaming-form-data == 1.5.1'
# python3 -c 'import streaming_form_data'
```

My system is Ubuntu 19.10 with system-provided Pythons 2.7.17rc1, 3.7.5, PyPy 2.7.13 and PyPy 3.6.1. I'm using a user-local repository (`--user`).

I think I'll need to debug this myself, since there seems to be no way for you to reproduce this. I will reopen if I find something that might need a change in `streaming-form-data`. Thanks and sorry for bothering!
