### ISSUE TITLE
Flask example file fails to run

### ISSUE THREAD

**Issue by ghost** [siddhantgoel/streaming-form-data#34]
```
$ python3 upload-test.py
Traceback (most recent call last):
  File "upload-test.py", line 10, in <module>
    from streaming_form_data import StreamingFormDataParser
  File "/usr/local/lib/python3.7/dist-packages/streaming_form_data/__init__.py", line 1, in <module>
    from streaming_form_data.parser import (  # NOQA
  File "/usr/local/lib/python3.7/dist-packages/streaming_form_data/parser.py", line 4, in <module>
    from streaming_form_data._parser import ErrorGroup, _Parser  # type: ignore
ImportError: /usr/local/lib/python3.7/dist-packages/streaming_form_data/_parser.so: undefined symbol: _Py_ZeroStruct

```
I used this:
https://github.com/siddhantgoel/streaming-form-data/blob/master/examples/flask/upload-test.py

**Comment by siddhantgoel** [comment]
We've had a similar issue before ([this one](https://github.com/siddhantgoel/streaming-form-data/issues/32)), which was because of the module being built against Python 2 but being run from Python 3 (or the other way around).

Are you using a virtualenv? If not, could you try creating a virtualenv with Python 3, and then pip installing the module and trying again?

**Comment by cipherninja** [comment]
Baremetal server using Debian headless on a Raspberry Pi 3. It stopped working after upgrading streaming-form-data to a later version (1.5.x) with pip.

**Comment by siddhantgoel** [comment]
Is it the installation that doesn't work? Or does it get installed but the examples don't run?

**Comment by cipherninja** [comment]
The python wheel always installs fine, it is the example that doesn't work with 1.5.x anymore. Which is why I removed all of the new code and wheels. I have to use the old versions.

**Comment by siddhantgoel** [comment]
And you're running it inside a virtualenv that has Python 3?

**Comment by cipherninja** [comment]
No virtualenv, that would defeat the benefits of a [bare-metal server](https://en.wikipedia.org/wiki/Bare-metal_server)
I did not require any virtualenv for v1.4.0 either.

**Comment by siddhantgoel** [comment]
> No virtualenv, that would defeat the benefits of a bare-metal server

Why would using virtualenv defeat the benefits of a bare-metal server?

> I did not require any virtualenv for v1.4.0 either.

Interesting. I've tried installing the versions from 1.4 onwards and seem to work fine here at my end. I wonder if there's a difference because of the C compiler being used to build the extension.
