### ISSUE TITLE
Register multiple targets per same part?

### ISSUE THREAD

**Issue by kenchilada** [siddhantgoel/streaming-form-data#36]
I have a scenario where I would like to capture a file upload and also a SHA256 hash of the SAME part of the request...

```        
        parser = StreamingFormDataParser(headers=request.headers)

        search_document = FileTarget(tmp.name)
        parser.register('SearchDocument', search_document)

        uploaded_file_sha256 = SHA256Target()
        parser.register('SearchDocument', uploaded_file_sha256)
```

Should this be supported?  It seems like the SHA target always has the same value after upload when I try this.  I am trying to avoid reading the file a second time from disk to generate a hash.

Thanks, this is a great project.

**Comment by siddhantgoel** [comment]
That sounds like a useful thing to have. I'll see if I can get to it in the next days.

**Comment by siddhantgoel** [comment]
I just pushed `v1.6.0` which allows this behavior. You should just be able to call `parser.register` multiple times for the same part.
