### ISSUE TITLE
No wheels deployed

### ISSUE THREAD

**Issue by Hobart2967** [siddhantgoel/streaming-form-data#37]
I get an error when installing the package due to missing wheels

ERROR: Could not build wheels for streaming-form-data which use PEP 517 and cannot be installed directly

https://packaging.python.org/tutorials/packaging-projects/

**Comment by siddhantgoel** [comment]
This package contains a C extension, and Poetry supports building [only pure Python wheels](https://python-poetry.org/docs/cli/#build). This is why we're only uploading source distributions to PyPI.

if you know of a workaround, let me know.

Btw, does installing from source not work for you? I (and also others) have been using `pip install streaming-form-data` and that seems to work in general. Could you paste the complete log of the command you tried and the error you got?

**Comment by fy0** [comment]
> Btw, does installing from source not work for you? I (and also others) have been using `pip install streaming-form-data` and that seems to work in general. Could you paste the complete log of the command you tried and the error you got?

wheels is much better for windows users.

**Comment by siddhantgoel** [comment]
Closing due to missing details.
