### ISSUE TITLE
Ubuntu Server slow speed

### ISSUE THREAD

**Issue by JeffSaa** [siddhantgoel/streaming-form-data#39]
Hi I first tried in MacOs and this is awesome but then I pull my code on Ubuntu and the speed is the same when I don't use this library

**Comment by siddhantgoel** [comment]
This needs more details. What exactly is the issue? Speed of what is not the same?

It would be helpful if you could describe what your environments (both macOS and Ubuntu) look like and what Python version are you using? Also, what does your code look like?
