### ISSUE TITLE
Checking for case insensitive Content-Type

### ISSUE THREAD

**Issue by guanzo** [siddhantgoel/streaming-form-data#4]
Hi, great library!

This line here checks for a case sensitive 'Content-Type':
https://github.com/siddhantgoel/streaming-form-data/blob/6fa2d23a3e5015a08144aa12903f206dc8cf49e7/streaming_form_data/parser.py#L10-L13

I was testing with curl and the browser, they both send the content type header as uppercase: 'CONTENT-TYPE', which causes this library to throw `ParseFailedException`. 

According to the http spec, headers are case-insensitive: https://stackoverflow.com/questions/7718476/are-http-headers-content-type-c-case-sensitive/7718542

It'd be great if you could make the dictionary `get` case insensitive.

**Comment by siddhantgoel** [comment]
Just uploaded `v0.4.5` with https://github.com/siddhantgoel/streaming-form-data/commit/2390e94f1b0e8ef13e4940173d2892b0df42d7e2 which includes this update!

**Comment by guanzo** [comment]
Wowow thanks for the quick fix!
