### ISSUE TITLE
How do you read file name?

### ISSUE THREAD

**Issue by harshithjv** [siddhantgoel/streaming-form-data#40]
Is there a way to read file name or content type before creating setting FileTarget?

It does not make treat each incoming stream as text when it could be binary stream most of the time?

**Comment by siddhantgoel** [comment]
The targets actually don't think of the incoming stream as text but instead treat everything as just raw bytes. The file name and content type is available as `self.multipart_filename` and `self.multipart_content_type` in the target objects.

Was that what you were looking for?

**Comment by harshithjv** [comment]
@siddhantgoel Thanks :)
