### ISSUE TITLE
low parsing speed

### ISSUE THREAD

**Issue by kolomenkin** [siddhantgoel/streaming-form-data#5]
Hi, I found the speed of the parser to be rather low.

My desktop i7 CPU is parsing only approx 30 MB/s.
And my intranet network is 1 Gbit. So I want this parser to work at least at 100 MB/s.

I will do better benchmark of current solution later.

I investigated the code and I'm sure I can do 100+ MB/s by changing cython code to be more C-like. So it will not read single bytes from Python objects, but will use raw C pointers instead.

Before starting work on pull request I want to ensure
1. speed improvements are important for you
2. rewriting cython code to more dangerous C-style code without bounds checking for every memory read operation is acceptable for this project in general

P.S. By the way, internal algorithm of matching boundaries in the stream is well done. It is very effective.

**Comment by kolomenkin** [comment]
And another question.
I saw hardcoded constant MaxBufferSize =1024.

I think we could do implement the module without the constant at all.
I think the better idea is to use existing incoming chunk sizes as expected chunk sizes for output.

So if the caller feeds the stream with 1K chunks - it is good idea to feed target with ~1K chunks too.
But if the caller feeds the stream with 1M chunks - it is good idea to feed target with ~1M chunks too.

If you agree with me, I could also rewrite this logic too.

So it could be few separate commits:
1) Rewrite to use dynamic target chunks
2) Add benchmark script + rewrite in C-style (speed optimization)

**Comment by siddhantgoel** [comment]
First off, thanks for looking into this! Speed issues (particularly when processing larger files) is something I'm aware of but just haven't had the time recently to look into. :100: 

1. Absolutely, speed improvements are extremely important.
2. Before doing a rewrite in C, I would propose reducing the number of Python-space operations that Cython is compiling. If you open `annotation.html` in a browser, the lines highlighted in yellow are the ones that Cython couldn't generate optimized code for. And as a result, the performance is not what it could be. I would love to see if there's a way to rewrite those highlighted lines using some other primitives that Cython provides, so we can get optimized code out.

In general I'm not at all opposed to C code if that's the only way out.

But I would first like to explore if there are incremental operations possible (like reducing the Python-space operations) that improve performance.

What do you think?

**Comment by siddhantgoel** [comment]
Good point regarding `MaxBufferSize`. As a first thought, getting rid of this constant could reduce the number of calls to `on_body`, which should improve things because that `for` loop is what's killing performance at the moment.

This should actually be verifiable using the `utils/benchmark.py` script (just give it a random file and content type and it should show you if things improved or not).

**Comment by kolomenkin** [comment]
I confused you. I do not want to rewrite in C,
I want to use cython, but change the code this way:

code style before (it makes a call to Python object)
```
bytes chunk
for idx in range(0, len(chunk))
    element = chunk[idx]
```
code style after
```
char *first, *last, current
for current in range(first, last)
    element = *current
```

**Comment by siddhantgoel** [comment]
Ah OK, understood. Yes, that sounds like a good plan. I'm super excited about the PR!

Follow-up question - do you think this would require additional testing beyond testing for correctness?

**Comment by kolomenkin** [comment]
I missed you already have benchmark script. Cool.

Thanks for pointing to annotation.html. This is really cool report.
I'm new to cython (I first have heard about it yesterday), but it is a cool extension for python. Usually I write in c++.

> do you think this would require additional testing beyond testing for correctness?

I would say yes. But it is hard to say how to test this well. The only idea is to try writing the code which can be verified by human as easy as possible (simple code).

Using raw pointers gives us a way to read unpredictable memory address.  This can crash application in case of mistake. I'm not going to write memory using raw pointers in your algorithm.

Usually C programs can be analyzed using [Valgrind](http://valgrind.org/)-like tools checking all memory operations.
Static code analysis tools ([like this](https://www.viva64.com/en/pvs-studio/)) can also help sometimes.
And another option is to run program under some [fuzzing tool](https://en.wikipedia.org/wiki/Software_testing#Destructive_testing).

**Comment by siddhantgoel** [comment]
I just pushed `v0.6.0` to PyPI, which includes the performance fixes you contributed. Thanks a lot!
