### ISSUE TITLE
How to use to read image file?

### ISSUE THREAD

**Issue by josiahcoad** [siddhantgoel/streaming-form-data#57]
Right now I have a block of code in my flask app:
```python
def read_image(request):
    import pdb; pdb.set_trace()
    file = request.files['image'] #fast_file_read(request) 
    img = Image.open(file.stream)
    return img
```

The line `file = request.files['image']` is taking a long time so I want to replace it with a function `fast_file_read(request)` that uses your library to speed up this line. Is this possible? I looked at the examples/flask and the best I could come up with is

```python
def fast_file_read(request):
    file_ = FileTarget(os.path.join(tempfile.gettempdir(), 'test'))
    parser = StreamingFormDataParser(headers=request.headers)
    parser.register('file', file_)
    while True:
        chunk = request.stream.read(8192)
        if not chunk:
            break
        parser.data_received(chunk)
    return file_
```

But it is giving me "AttributeError: 'FileTarget' object has no attribute 'stream'"

**Comment by siddhantgoel** [comment]
At which line do you see the `AttributeError`? If it's possible, could you paste the complete code as well as the full stacktrace you run into?

**Comment by siddhantgoel** [comment]
I'll mark this as closed for now. Feel free to reopen when you have the full stacktrace for debugging.
