### ISSUE TITLE
Move C declarations to a .pxd file to be available to other Cython modules.

### ISSUE THREAD

**Issue by Mng-dev-ai** [siddhantgoel/streaming-form-data#59]
I think It would be great if you move the c declarations to a .pxd file to be available to other cython modules as in my case I don't need to use it as a python module to minimize the python interactions as possible.

**Comment by siddhantgoel** [comment]
It could be a good idea. Could you please describe your use case a bit more?

**Comment by Mng-dev-ai** [comment]
I'm working on cython project and I'm gonna use your package so I wanna be able to import it as a cython module which is not possible without using .pxd file

**Comment by Mng-dev-ai** [comment]
I may can work on a pr if you want

**Comment by siddhantgoel** [comment]
Yeah that would be helpful. And as I understand, you're planning to move only the C declarations to that file, right? So the `Finder` and `_Parser` classes stay?

**Comment by Mng-dev-ai** [comment]
Yes, the class itself will be the same but the declarations such `cdef bytes target` will be moved.

**Comment by siddhantgoel** [comment]
Sounds good. Let's do it!

**Comment by Mng-dev-ai** [comment]
Done at #60

**Comment by siddhantgoel** [comment]
I'll close this for now as #60 hasn't seen any updates. Feel free to reopen when the PR is updated.
