### ISSUE TITLE
`cgi` is being deprecated in 3.13

### ISSUE THREAD

**Issue by jasopolis** [siddhantgoel/streaming-form-data#71]
https://peps.python.org/pep-0594/#cgi

The official docs suggest to replace `cgi.parse_header` with `email.message.Message`:

> As an explicit example of how close parse_header and email.message.Message are:
> ```
> >>> from cgi import parse_header
> >>> from email.message import Message
> >>> parse_header(h)
> ('application/json', {'charset': 'utf8'})
> >>> m = Message()
> >>> m['content-type'] = h
> >>> m.get_params()
> [('application/json', ''), ('charset', 'utf8')]
> >>> m.get_param('charset')
> 'utf8'
> ```

@siddhantgoel I'm happy to take a shot at the PR if you're accepting them!

**Comment by siddhantgoel** [comment]
Ah cool, good to know. Yes, a PR for this would be nice!
