### ISSUE TITLE
How to validate content-type?

### ISSUE THREAD

**Issue by vitor-amartins** [siddhantgoel/streaming-form-data#82]
I'm using S3Target to upload a file directly to S3. But I want to validate the content-type to allow only certain extensions (pdf, jpeg, png, docx, xlxs and pptx)

I'm not sure how should I use `multipart_content_type` to validate this. Can you guys help me?

I'm using FastAPI as web framework.

```python
parser = StreamingFormDataParser(headers=request.headers)
target = S3Target(
    file_path=file_path,
    mode='wb',
    transport_params={'client': self._client},
    validator=MaxSizeValidator(self.max_file_size),
)
parser.register('file', target)
async for chunk in request.stream():
    body_validator(chunk)
    parser.data_received(chunk)
```

**Comment by siddhantgoel** [comment]
You can read the filename using `target.multipart_filename` and then extract the extension (eg. `pathlib.path(target.multipart_filename).suffix`) to perform the check.

**Comment by siddhantgoel** [comment]
> It worked fine on my local tests, but I still couldn't test to all the types of files that I want to allow.

Do you mean that you're getting different results when the app is deployed v/s locally? If that's the case, I think python-magic uses libmagic underneath to determine the content type so there might be a few different locations to check what exactly is returning `application/octetstream`.

Out of curiosity: could you confirm that you're not running into https://github.com/ahupp/python-magic/blob/master/magic/__init__.py#L128-L135?

**Comment by vitor-amartins** [comment]
> Do you mean that you're getting different results when the app is deployed v/s locally? If that's the case, I think python-magic uses libmagic underneath to determine the content type so there might be a few different locations to check what exactly is returning `application/octetstream`.

Sorry about that, I think I expressed myself poorly. The snippet I put here seems to be working fine. But before I get to it, I was trying to identify the mime while reading, inside this loop:
```python
async for chunk in request.stream():
    body_validator(chunk)
    parser.data_received(chunk)
```
And it was just returning `application/octetstream`, I really don't know why it had this behaviour, I don't know if the chunks are not provided starting exactly from the range 0, and because of that it could define correctly or if it's anything else.

But when I tried to get the mime type from the file uploaded to S3, it worked fine.

> It worked fine on my local tests, but I still couldn't test to all the types of files that I want to allow.

Here I was just clarifying that I couldn't test yet if it works every time for the files I want.

Now I'm only wondering if I could identify before totally uploading to S3, so in a use case that user could upload a big file, it wouldn't have to wait the whole upload to raise this exception.

**Comment by siddhantgoel** [comment]
Ah, got it. Thanks for the explanation.

It seems like [the only case](https://github.com/search?q=repo%3Aahupp%2Fpython-magic%20%22application%2Foctet-stream%22&type=code) where python-magic returns `application/octet-stream` is the exception case which I linked to earlier, which would mean that the problem might be on libmagic's end.

Could you maybe confirm that you're not running libmagic 5.09?

> I don't know if the chunks are not provided starting exactly from the range 0

I think you should be able to verify this, if you upload a file and write out the bytes to a file on disk and compare it later to what was uploaded.

**Comment by siddhantgoel** [comment]
Cool! It looks fine to me. :) I'll close this issue in that case but feel free to reopen if something else related comes up.
